server.address=0.0.0.0
server.port=8080
server.servlet.context-path=/api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_UPASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public

spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.pool-name=SpringBootHikariCP

com.illia.carrental.auth.authentication-url=${CARRENTAL_AUTHENTICATION_URL}
com.illia.carrental.auth.client-secret=${CARRENTAL_AUTHENTICATION_CLIENT_SECRET}

com.illia.carrental.payment.create-payment-link-url=${CARRENTAL_PAYMENTS_URL}
com.illia.carrental.payment.client-secret=${CARRENTAL_PAYMENTS_CLIENT_SECRET}
